#include "mqtt-attacker.h"

#include "ns3/core-module.h"

#include "mqtt-wire.h"
#include "research-payload.h"
#include "scenario-state.h"

using namespace ns3;

void
AttackerConnectSucceeded(Ptr<Socket> socket)
{
    std::string clientId = "security-game-attacker";

    if (g_attackKind == AttackKind::REPLAY)
    {
        clientId = "compromised-replay-client";
    }
    else if (g_attackKind == AttackKind::INJECTION)
    {
        clientId = "unauthorized-injection-client";
    }
    else if (g_attackKind == AttackKind::DOS)
    {
        clientId = "compromised-dos-client";
    }

    socket->Send(Mqtt::ToNs3Packet(
        Mqtt::BuildConnect(clientId)));

    ++g_state.connectPacketsSent;
}

void
AttackerConnectFailed(Ptr<Socket>)
{
    NS_FATAL_ERROR("Attacker TCP connection to broker failed");
}

void
HandleAttackerRead(Ptr<Socket> socket)
{
    while (Ptr<Packet> p = socket->Recv())
    {
        if (p->GetSize() == 0)
        {
            break;
        }

        const size_t oldSize = g_attackerBuffer.size();
        g_attackerBuffer.resize(oldSize + p->GetSize());

        p->CopyData(
            g_attackerBuffer.data() + oldSize,
            p->GetSize());

        Mqtt::PacketView packet;

        while (Mqtt::TryExtractPacket(g_attackerBuffer, packet))
        {
            if (packet.type ==
                static_cast<uint8_t>(Mqtt::Type::CONNACK))
            {
                if (packet.body.size() == 2 &&
                    packet.body[1] == 0x00)
                {
                    g_attackerMqttConnected = true;
                    ++g_state.connackPacketsReceived;
                }
                else
                {
                    ++g_state.malformedPackets;
                }
            }
            else if (packet.type ==
                     static_cast<uint8_t>(Mqtt::Type::PUBACK))
            {
                uint16_t packetId = 0;

                if (Mqtt::ParsePacketIdentifier(packet, packetId))
                {
                    ++g_state.attackerPubacksReceived;
                }
                else
                {
                    ++g_state.malformedPackets;
                }
            }
            else
            {
                ++g_state.unexpectedPackets;
            }
        }
    }
}

void
SendAttackMessage()
{
    if (g_attackKind == AttackKind::NONE ||
        Simulator::Now() >= g_attackStop)
    {
        return;
    }

    if (!g_attackerMqttConnected)
    {
        Simulator::Schedule(
            MilliSeconds(10),
            &SendAttackMessage);
        return;
    }

    if (g_attackKind != AttackKind::DOS &&
        g_attackMessagesScheduled >= g_attackCount)
    {
        return;
    }

    uint32_t publisherId = INJECTION_PUBLISHER_ID;
    uint64_t sequence = g_nextAttackSequence++;
    std::vector<uint8_t> payload;

    if (g_attackKind == AttackKind::REPLAY)
    {
        if (!g_replayPayloadCaptured)
        {
            Simulator::Schedule(
                MilliSeconds(10),
                &SendAttackMessage);
            return;
        }

        // Replay preserves application metadata/payload but gets a fresh MQTT
        // Packet Identifier because it is a new QoS 1 transaction.
        payload = g_capturedReplayPayload;
    }
    else if (g_attackKind == AttackKind::INJECTION)
    {
        payload = CreateResearchPayload(
            INJECTION_PUBLISHER_ID,
            sequence,
            g_payloadBytes);
    }
    else
    {
        // DoS is generated by an authorized/compromised client. It uses the
        // legitimate publisher identity in the research payload but comes from
        // the attacker's TCP endpoint and at a high rate.
        publisherId = LEGITIMATE_PUBLISHER_ID;
        payload = CreateResearchPayload(
            publisherId,
            sequence,
            g_payloadBytes);
    }

    const uint16_t packetId =
        NextPacketId(g_nextAttackerPacketId);

    const std::vector<uint8_t> mqttPacket =
        Mqtt::BuildPublishQos1(
            MQTT_TOPIC,
            packetId,
            payload);

    const int sent =
        g_attackerSocket->Send(
            Mqtt::ToNs3Packet(mqttPacket));

    if (sent > 0)
    {
        ++g_state.attackerMessagesSent;
        ++g_attackMessagesScheduled;
    }

    if (g_attackKind == AttackKind::DOS)
    {
        Simulator::Schedule(
            Seconds(1.0 / g_attackRateHz),
            &SendAttackMessage);
    }
    else if (g_attackMessagesScheduled < g_attackCount)
    {
        Simulator::Schedule(
            Seconds(1.0 / g_attackRateHz),
            &SendAttackMessage);
    }
}
